spring:
  application:
    name: user-service

  mongodb:
    uri: mongodb+srv://nguyenhung2004200_db_user:W87UoUWquGGfbjXv@cluster1.gypblkl.mongodb.net/userdb?retryWrites=true&w=majority&authSource=admin

  rabbitmq:
    host: kingfisher.lmq.cloudamqp.com
    port: 5672
    username: mwdpomue
    password: DI1u8Xz2UHOWm1yqlxmZCz7H40MDCe06
    virtual-host: mwdpomue
    ssl:
      enabled: true

server:
  port: 8081

jwt:
  secret: your_super_secret_key_12345678901234567890
  expiration: 86400000
