spring:
  application:
    name: user-service

  mongodb:
    uri: "mongodb+srv://nguyenhung2004200_db_user:W87UoUWquGGfbjXv@cluster1.gypblkl.mongodb.net/userdb?retryWrites=true&w=majority"
    database: ${SPRING_MONGODB_DATABASE:userdb}

  rabbitmq:
    host: kingfisher.lmq.cloudamqp.com
    port: 5672
    username: mwdpomue
    password: DI1u8Xz2UHOWm1yqlxmZCz7H40MDCe06
    virtual-host: mwdpomue
    ssl:
      enabled: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:your_super_secret_key_1234567890123456}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  default-admin:
    enabled: ${DEFAULT_ADMIN_ENABLED:true}
    full-name: ${DEFAULT_ADMIN_FULL_NAME:System Admin}
    email: ${DEFAULT_ADMIN_EMAIL:admin@movie.com}
    password: ${DEFAULT_ADMIN_PASSWORD:Admin@123456}

logging:
  level:
    com.movie.userservice: INFO
